version: "3"
services:
  app:
    build: 
      context: .
    container_name: app
    volumes:
      - ./logs:/var/log/secretaria
    ports:
      - "8080:8080"
    env_file: ./secret.env

  postgres:
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    container_name: postgres14
    environment:
      - POSTGRES_DB=secretaria
      - POSTGRES_USER=smarchz
      - TZ='GMT+7'
      - PGTZ='GMT+7'
    env_file: ./secret.env
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata:
